"""WebUI 配置项展示用中文名。"""

from __future__ import annotations

# 键为 Pydantic 字段名；插件与通用配置共用。
FIELD_LABELS: dict[str, str] = {
    "ai_server_host": "AI 服务主机",
    "ai_server_port": "AI 服务端口",
    "answer_threshold": "接话随机阈值",
    "answer_threshold_weights": "接话阈值权重",
    "api_key": "备线访问密钥",
    "auto_enroll": "自动获取社区访问口令",
    "base_url": "备线服务地址",
    "bootstrap_url": "多机协同中心地址",
    "bot_status_list_mode": "在吗名册模式",
    "bot_status_notice_email": "告警收件邮箱",
    "bot_status_offline_grace_time": "离线宽限（分钟）",
    "bots": "已连接牛牛 QQ 集合",
    "chat_enable": "启用酒后聊天（遗留 RWKV，请改用 LLM_CHAT_ENABLED）",
    "chat_endpoint": "聊天接口路径",
    "claim_ttl_sec": "去重保留秒数",
    "command_limit_overrides": "命令冷却覆盖",
    "command_permission_overrides": "命令权限覆盖",
    "community_api_base": "共享语料服务地址",
    "community_contribute": "把新学到的回复上传到社区",
    "corpus_backfill_batch_size": "每轮同步条数",
    "corpus_backfill_enabled": "把历史语料同步到社区",
    "corpus_backfill_interval_sec": "同步间隔（秒）",
    "corpus_backfill_max_per_minute": "同步限速（次/分钟）",
    "community_enabled": "使用社区共享接话库",
    "community_stats_enabled": "上报在线统计",
    "community_stats_endpoint": "统计上报地址",
    "community_stats_interval_sec": "上报间隔",
    "community_stats_roster_public_qq": "公开牛牛 QQ",
    "community_stats_roster_public_profile": "公开牛牛头像昵称",
    "community_stats_token": "统计上报口令",
    "community_token": "共享语料访问口令",
    "coord_redis_url": "多进程共用去重服务地址",
    "cross_group_threshold": "跨群提升语料阈值",
    "custom_styles": "自定义样式列表",
    "default_style": "默认帮助样式",
    "default_styles": "内置样式列表",
    "del_session_endpoint": "清除会话路径",
    "dream_archive_image_probability": "带图概率",
    "dream_drift_queue_tick_probability": "漂流队列推进概率",
    "dream_echo_resample_attempts": "回声重采样次数",
    "dream_hist_resample_attempts": "历史梦重采样次数",
    "dream_history_recency_power": "历史梦新近权重",
    "dream_history_recent_dedupe_max": "近期梦去重条数",
    "dream_message_retention_days": "梦消息保留天数",
    "dream_prefer_learned_echo_probability": "优先已学回声概率",
    "dream_worker_sleep_max_sec": "做梦线程最长休眠（秒）",
    "dream_worker_sleep_min_sec": "做梦线程最短休眠（秒）",
    "drunk_tts_threshold": "醉酒转语音字数",
    "duel_auto_sync_operators": "启动同步干员表",
    "duel_avatar_download_on_startup": "启动批量下载头像",
    "duel_avatar_download_on_use": "用时下载头像",
    "duel_bot_cooldown_sec": "决斗冷却（秒）",
    "duel_bot_qte_fail_silent_chance": "QTE 失败沉默概率",
    "duel_bot_qte_fail_speak_wrong_chance": "QTE 失败乱说话概率",
    "duel_bot_qte_intrusion_success_rate": "牛 QTE 乱入成功率",
    "duel_bot_qte_keyword_success_rate": "牛 QTE 口令成功率",
    "duel_compact_round": "紧凑回合发群",
    "duel_exchange_qte_chance": "QTE 额外触发概率",
    "duel_exchange_qte_race_chance": "QTE 抢答概率",
    "duel_intrusion_pallas_roll_chance": "帕拉斯乱入概率",
    "duel_intrusion_race_chance": "乱入抢答概率",
    "duel_operator_intrusion_chance": "干员乱入概率",
    "duel_penalty_bot_fake_msg": "牛牛败北台词",
    "duel_penalty_bot_sad_msg": "牛牛败北沉默台词",
    "duel_penalty_human_noise_msg": "人败北台词",
    "duel_penalty_loser_card": "败者群名片",
    "duel_penalty_minutes": "败者禁言时长（分钟）",
    "duel_penalty_winner_card": "胜者群名片",
    "duel_player_rounds_max": "玩家回合上限",
    "duel_public_round_weight": "公开回合权重",
    "duel_public_terra_weight_mult": "公开地形权重倍率",
    "duel_qte_event_weight_mult": "QTE 事件权重倍率",
    "duel_round_pause_max_sec": "回合间最长暂停（秒）",
    "duel_round_pause_min_sec": "回合间最短暂停（秒）",
    "duel_total_rounds": "默认总回合数",
    "duplicate_reply": "回复去重轮数",
    "enable_auto_reply_on_reaction": "跟他人表情回应",
    "enable_custom_style_loading": "加载自定义样式",
    "enable_face_reaction": "QQ表情自动回应",
    "enable_kick_ban": "被踢出群时加入黑名单",
    "enable_probability_reaction": "随机表情回应",
    "enable_reaction": "启用表情回应",
    "enabled": "启用多机协同",
    "fanout_enabled": "多只牛牛同群时一起接话",
    "fanout_max_bots": "同群接话时最多参与几只牛",
    "group_style_enabled": "启用群风格自动生长",
    "fed_contribute": "把本群新回复分享给社区",
    "fed_enabled": "使用社区共享接话库",
    "federate_id": "本站在社区中的编号",
    "federate_ingress_enabled": "多机部署时过滤重复群消息",
    "federate_redis_prefix": "去重键前缀",
    "find_cache_max": "查询缓存条数上限",
    "find_cache_ttl_sec": "查询缓存保留秒数",
    "greeting_fanout_texts": "全员同响口令列表",
    "dispatch_lanes_enabled": "限制同时处理的消息数量",
    "lane_acquire_timeout_sec": "排队等待超时（秒）",
    "lane_busy_reply": "太忙时的自动回复",
    "lane_chat": "闲聊类同时处理上限",
    "lane_command": "口令类同时处理上限",
    "lane_remote": "访问外网服务同时处理上限",
    "lane_storage": "读写数据库同时处理上限",
    "lane_wait_overload_ms": "排队过久判定阈值（毫秒）",
    "matcher_dispatch_enabled": "先筛掉与牛牛无关的消息",
    "matcher_dispatch_overload_threshold": "预筛过载阈值",
    "route_index_enabled": "口令快速定位（推荐开启）",
    "route_index_strict": "只响应已登记的口令",
    "send_queue_enabled": "发送消息排队（防刷屏）",
    "send_queue_enqueue_timeout_sec": "排队发送超时（秒）",
    "send_queue_max_depth": "待发消息队列长度",
    "send_queue_min_interval_ms": "同一只牛最短发送间隔（毫秒）",
    "send_queue_workers": "发送消息的工作线程数",
    "ignored_plugins": "隐藏插件列表",
    "inbound_filter_api_fail_open": "审查失败时放行",
    "inbound_filter_api_key": "审查接口密钥",
    "inbound_filter_api_timeout_sec": "审查超时（秒）",
    "inbound_filter_api_url": "审查接口（备用）",
    "inbound_filter_substrings": "关键词拦截",
    "ingress_bypass_unified": "单进程运行时跳过消息预筛",
    "instance_secret": "加入协同的密钥",
    "learn_concurrency": "后台学习并发数",
    "learn_queue_max_size": "学习队列容量",
    "maa_attach_screenshot": "指令后自动截图",
    "maa_combat_auto_prepare": "作战前自动准备",
    "maa_get_task_endpoint": "取任务完整地址",
    "maa_get_task_path": "取任务路径",
    "maa_public_base_url": "对外访问地址",
    "maa_report_status_endpoint": "报状态完整地址",
    "maa_report_status_path": "报状态路径",
    "maa_seen_ttl_seconds": "未绑定设备保留（秒）",
    "merge_order": "接话查找顺序",
    "merge_strategy": "重复句如何合并",
    "model": "备线模型名",
    "name": "备线显示名",
    "llm_chat_enable": "启用 LLM 闲聊（已弃用，请用 LLM_CHAT_ENABLED）",
    "llm_chat_enabled": "启用智能对话（总开关）",
    "llm_repeater_mode": "接话时如何使用智能对话",
    "llm_select_enabled": "命中语料后用 AI 按语境选句（推荐）",
    "llm_select_max_candidates": "选句提交给 AI 的候选句上限",
    "llm_polish_lite_sample_rate": "偶尔轻润色的比例",
    "llm_fallback_enabled": "语料里没有合适回复时用 AI 现编（遗留项）",
    "llm_polish_enabled": "命中语料后用 AI 润色措辞（遗留项）",
    "llm_governance_enabled": "限制闲聊频率与字数",
    "llm_chat_max_concurrency": "闲聊并发上限（每 worker）",
    "llm_repeater_group_cooldown_sec": "接话 AI 群冷却（秒）",
    "llm_repeater_max_inflight": "接话 AI 并发（每 worker）",
    "llm_repeater_global_rpm": "接话 AI 全局限流（次/分钟）",
    "llm_repeater_feedback_enabled": "收集闲聊反哺接话软反馈",
    "llm_repeater_bias_enabled": "让闲聊软反馈参与接话弱打分",
    "llm_repeater_writeback_enabled": "允许闲聊回复回写接话主学习库",
    "conversation_feature_level": "对话内核能力档位",
    "llm_reply_gate_enabled": "过滤无意义 @（门控）",
    "llm_chat_queue_merge": "冷却期合并多条 @",
    "llm_memory_rag_enabled": "群记忆检索（记住口令）",
    "llm_relationship_notes_enabled": "关系备注层（记住关系口令）",
    "llm_session_enabled": "记住多轮对话上下文",
    "llm_chat_system_prompt_path": "系统提示词文件",
    "llm_chat_min_priority": "闲聊指令优先级",
    "llm_chat_endpoint": "闲聊接口路径",
    "llm_del_session_endpoint": "清除会话路径",
    "ollama_chat_endpoint": "闲聊接口路径（已弃用）",
    "ollama_del_session_endpoint": "清除会话路径（已弃用）",
    "ollama_enable": "启用 LLM 闲聊（已弃用键名）",
    "ollama_min_priority": "闲聊指令优先级（已弃用）",
    "ollama_system_prompt_path": "系统提示词文件（已弃用）",
    "omit_response_format": "备线省略返回格式",
    "on_remote_failure": "远端失败策略",
    "pallas_image_api_backends": "备用网关",
    "pallas_image_api_key": "主网关密钥",
    "pallas_image_aspect_ratio": "画幅比例",
    "pallas_image_base_url": "主服务地址",
    "pallas_image_default_edit_prompt": "编辑默认提示词",
    "pallas_image_draw_command_cooldown": "群冷却（秒）",
    "pallas_image_draw_group_whitelist": "群白名单",
    "pallas_image_draw_max_pending": "排队上限",
    "pallas_image_draw_per_user_limit": "每日次数上限",
    "pallas_image_draw_total_timeout": "总超时（秒）",
    "pallas_image_backend_attempt_timeout": "备用网关超时（秒）",
    "pallas_image_draw_unlimited_group_ids": "无限次数群",
    "pallas_image_draw_unlimited_user_ids": "无限次数用户",
    "pallas_image_http_transport": "HTTP 客户端",
    "pallas_image_http_user_agent": "User-Agent",
    "pallas_image_max_concurrency": "全局并发上限",
    "pallas_image_max_param_attempts": "参数尝试上限",
    "pallas_image_merge_reference_urls_into_prompt": "参考图写进提示词",
    "pallas_image_min_priority": "指令优先级",
    "pallas_image_model": "默认模型",
    "pallas_image_primary_name": "主网关名称",
    "pallas_image_quality": "生成质量",
    "pallas_image_ref_download_timeout": "参考图超时（秒）",
    "pallas_image_request_timeout": "请求超时（秒）",
    "pallas_image_response_format": "返回格式",
    "pallas_image_size": "像素尺寸",
    "pallas_image_slow_param_fallback": "失败试慢档",
    "pallas_image_tls_impersonate": "TLS 指纹",
    "pallas_image_use_edits_for_reference_images": "参考图走编辑",
    "pallas_protocol_auto_download_runtime": "缺少时自动下载",
    "pallas_protocol_bind_host": "本地监听地址",
    "pallas_protocol_default_args": "启动命令参数",
    "pallas_protocol_default_command": "NapCat 启动命令",
    "pallas_protocol_default_working_dir": "子进程工作目录",
    "pallas_protocol_docker_gid": "容器运行 GID",
    "pallas_protocol_docker_image": "NapCat Docker 镜像",
    "pallas_protocol_docker_internal_webui_port": "容器内网页端口",
    "pallas_protocol_docker_memory_limit": "容器内存上限",
    "pallas_protocol_docker_memory_swap": "容器 swap 上限",
    "pallas_protocol_docker_network_mode": "Docker 网络模式",
    "pallas_protocol_docker_onebot_host": "容器访问宿主机地址",
    "pallas_protocol_docker_shm_size": "容器共享内存大小",
    "pallas_protocol_docker_uid": "容器运行 UID",
    "pallas_protocol_enabled": "启用协议端管理",
    "pallas_protocol_follow_bot_lifecycle": "随牛牛启停实例",
    "pallas_protocol_github_repo": "NapCat 下载仓库",
    "pallas_protocol_github_token": "GitHub 下载令牌",
    "pallas_protocol_instances_root": "实例数据总目录",
    "pallas_protocol_linux_appimage_args": "AppImage 启动参数",
    "pallas_protocol_linux_use_docker": "Linux 用 Docker 跑 NapCat",
    "pallas_protocol_linux_use_xvfb": "Linux 用虚拟显示器",
    "pallas_protocol_linux_xvfb_args": "虚拟显示器参数",
    "pallas_protocol_linux_xvfb_command": "虚拟显示器命令",
    "pallas_protocol_max_log_lines": "协议日志行数上限",
    "pallas_protocol_onebot_client_name": "连接牛牛名称",
    "pallas_protocol_onebot_ws_host": "牛牛 WS 主机",
    "pallas_protocol_onebot_ws_path": "牛牛 WS 路径",
    "pallas_protocol_onebot_ws_port": "牛牛 WS 端口",
    "pallas_protocol_onebot_ws_url": "牛牛完整 WS 地址",
    "pallas_protocol_program_dir": "NapCat 程序目录",
    "pallas_protocol_release_asset": "NapCat 发布包名",
    "pallas_protocol_release_tag": "NapCat 版本标签",
    "pallas_protocol_shell_template_dir": "启动脚本模板目录",
    "pallas_protocol_snowluma_docker_auto_aux_bind_hi": "辅助端口上限",
    "pallas_protocol_snowluma_docker_auto_aux_bind_lo": "辅助端口下限",
    "pallas_protocol_snowluma_docker_auto_bind_port_hi": "自动绑定端口上限",
    "pallas_protocol_snowluma_docker_auto_bind_port_lo": "自动绑定端口下限",
    "pallas_protocol_snowluma_docker_host_novnc_port": "宿主机 noVNC 端口",
    "pallas_protocol_snowluma_docker_host_vnc_port": "宿主机 VNC 端口",
    "pallas_protocol_snowluma_docker_image": "SnowLuma Docker 镜像",
    "pallas_protocol_snowluma_docker_internal_novnc_port": "容器 noVNC 端口",
    "pallas_protocol_snowluma_docker_internal_onebot_http_port": "SnowLuma HTTP 端口",
    "pallas_protocol_snowluma_docker_internal_onebot_ws_port": "SnowLuma WS 端口",
    "pallas_protocol_snowluma_docker_internal_vnc_port": "容器 VNC 端口",
    "pallas_protocol_snowluma_docker_internal_webui_port": "SnowLuma 容器网页端口",
    "pallas_protocol_snowluma_docker_shm_size": "SnowLuma 共享内存",
    "pallas_protocol_snowluma_docker_vnc_passwd": "VNC 登录密码",
    "pallas_protocol_snowluma_github_repo": "SnowLuma 下载仓库",
    "pallas_protocol_snowluma_linux_use_docker": "Linux 用 Docker 跑 SnowLuma",
    "pallas_protocol_snowluma_program_dir": "SnowLuma 程序目录",
    "pallas_protocol_snowluma_release_asset": "SnowLuma 发布包名",
    "pallas_protocol_snowluma_release_tag": "SnowLuma 版本标签",
    "pallas_protocol_web_implementation": "协议网页实现",
    "pallas_protocol_webui_enabled": "启用协议端网页",
    "pallas_protocol_webui_path": "自定义网页挂载路径",
    "pallas_protocol_webui_port_max": "网页端口上限",
    "pallas_protocol_webui_port_min": "网页端口下限",
    "pallas_webui_allowed_origins": "允许的来源列表",
    "pallas_webui_cors": "允许跨域访问",
    "pallas_webui_dev_mode": "开发模式（跳过登录）",
    "pallas_webui_dist_zip_asset": "前端压缩包文件名",
    "pallas_webui_dist_zip_repo": "前端 GitHub 仓库",
    "pallas_webui_dist_zip_tag": "前端发布版本",
    "pallas_webui_dist_zip_url": "前端包直链",
    "pallas_webui_enabled": "启用网页控制台",
    "pallas_webui_http_base": "控制台路径前缀",
    "pallas_webui_log_lines_max": "运行日志行数上限",
    "path": "样式目录路径",
    "play_endpoint": "播放接口路径",
    "reaction_probability": "表情回应概率",
    "remote_find_enabled": "本机没有时查社区",
    "repeat_ignore_user_ids": "复读忽略 QQ 列表",
    "repeat_threshold": "复读触发次数",
    "reply_answers_cap": "接话候选条数上限",
    "reply_messages_cap": "接话历史条数上限",
    "reply_snapshot_max": "接话快照条数上限",
    "reply_snapshot_ttl_sec": "接话快照保留秒数",
    "reply_with_same_emoji": "跟回应用相同表情",
    "request_endpoint": "唱歌请求路径",
    "request_handler_notify_superusers": "通知超管审批",
    "request_handler_poll_doubt_friends": "轮询可疑好友",
    "save_count_threshold": "持久化消息条数",
    "save_reserved_size": "持久化后保留条数",
    "save_time_threshold": "持久化时间间隔（秒）",
    "scrub_api_url": "自建审查接口",
    "scrub_baidu_api_key": "百度 API Key",
    "scrub_baidu_block_suspected": "疑似违规也拦截",
    "scrub_baidu_censor_url": "百度接口地址",
    "scrub_baidu_secret_key": "百度 Secret Key",
    "scrub_baidu_strategy_id": "百度策略编号",
    "scrub_lexicon_extra": "追加敏感词",
    "scrub_lexicon_path": "词表文件路径",
    "scrub_review_providers": "在线审查顺序",
    "scrub_review_providers_key_present": "已配置在线审查（只读）",
    "side_paint_auto_page": "长文自动分页",
    "side_paint_enabled": "帮助图侧立绘",
    "side_paint_filename": "立绘文件名",
    "side_paint_scale": "立绘缩放倍数",
    "sing_enable": "启用唱歌点歌",
    "sing_endpoint": "合成任务路径",
    "sing_length": "默认合成时长（秒）",
    "sing_speakers": "音色映射",
    "smtp_password": "SMTP 密码",
    "smtp_port": "SMTP 端口",
    "smtp_server": "SMTP 服务器",
    "smtp_user": "SMTP 发信账号",
    "speak_continuously_max_len": "连说最多句数",
    "speak_continuously_probability": "连说概率",
    "speak_poke_probability": "发言戳一戳概率",
    "speak_threshold": "主动发言阈值",
    "split_probability": "拆句发送概率",
    "spy_default_blanks": "默认白板人数",
    "spy_default_undercovers": "默认卧底人数",
    "spy_email_fallback": "私聊失败改发邮箱",
    "spy_max_players": "房间人数上限",
    "spy_min_players": "最少开局人数",
    "spy_room_cleanup_sec": "空房清理等待（秒）",
    "spy_show_role_default": "私聊附带身份",
    "spy_auto_vote_when_all_spoken": "全员述词后自动投票",
    "spy_speak_max_len": "述词复盘单条字数上限",
    "spy_word_avoid_recent": "同群词对去重局数",
    "topics_importance": "关键词命中加成",
    "topics_size": "上下文关键词条数",
    "tts_enable": "醉酒后发语音回复",
}


def webui_field_label(field_name: str) -> str:
    return FIELD_LABELS.get(field_name, "")
